apiVersion: v1
kind: ServiceAccount
metadata:
  name: vktty-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: api-cluster-role
rules:
  - apiGroups:
        - ""
        - apps
        - autoscaling
        - batch
        - extensions
        - policy
        - rbac.authorization.k8s.io
    resources:
      - pods
      - componentstatuses
      - configmaps
      - daemonsets
      - deployments
      - events
      - endpoints
      - horizontalpodautoscalers
      - ingress
      - jobs
      - limitranges
      - namespaces
      - nodes
      - pods
      - persistentvolumes
      - persistentvolumeclaims
      - resourcequotas
      - replicasets
      - replicationcontrollers
      - serviceaccounts
      - services
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: api-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: vktty-sa
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin 
---
apiVersion: v1 
kind: Pod 
metadata: 
  name: ktty
  labels:
    app: ktty
spec: 
  serviceAccountName: vktty-sa
  containers: 
  - name: ktty 
    image: krkr/ktty:latest
    stdin: true 
    tty: true
    ports:
    - containerPort: 8042
---
apiVersion: v1
kind: Service
metadata:
  name: ktty
spec:
  type: NodePort
  selector:
    app: ktty
  ports:
  - protocol: TCP
    port: 8042
    nodePort: 31320
