apiVersion: v1
kind: Namespace
metadata:
  name: vktty
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vktty-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vktty-cluster-admin-role-binding
subjects:
- kind: ServiceAccount
  name: vktty-sa
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin 
---
apiVersion: v1 
kind: Pod 
metadata: 
  name: vktty
  namespace: default
  labels:
    app: vktty
spec: 
  serviceAccountName: vktty-sa
  containers: 
  - name: vktty 
    image: krkr/vktty:latest
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: vktty
  namespace: default
spec:
  type: NodePort
  selector:
    app: vktty
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 31319
